<?php

return [
    'home'                  => 'Trang chủ',
    'online'                => 'online',
    'login'                 => 'Đăng nhập',
    'logout'                => 'Đăng xuất',
    'setting'               => 'Cài đặt',
    'change_password'       => 'Đổi MK',
    'name'                  => 'Tên',
    'fullname'              => 'Tên đầy đủ',
    'email'                 => 'Email',
    'username'              => 'Tên đăng nhập',
    'password'              => 'Mật khẩu',
    'password_confirmation' => 'Nhập lại mật khẩu',
    'remember_me'           => 'Nhớ password',
    'user_setting'          => 'Cài đặt người dùng',
    'avatar'                => 'Hình đại diện',
    'list'                  => 'Danh sách',
    'new'                   => 'Mới',
    'create'                => 'Tạo',
    'delete'                => 'Xóa',
    'remove'                => 'Xóa',
    'edit'                  => 'Sửa',
    'continue_editing'      => 'Tiếp tục chỉnh sửa',
    'view'                  => 'Xem',
    'detail'                => 'Chi tiết',
    'browse'                => 'Duyệt',
    'reset'                 => 'Đặt lại',
    'export'                => 'Xuất file',
    'batch_delete'          => 'Xóa hàng loạt',
    'save'                  => 'Lưu',
    'refresh'               => 'Làm mới',
    'order'                 => 'Sắp xếp',
    'expand'                => 'Mở rộng',
    'collapse'              => 'Thu gọn',
    'filter'                => 'lọc',
    'search'                => 'Tìm kiếm',
    'close'                 => 'Đóng',
    'show'                  => 'Hiển thị',
    'entries'               => 'Mục',
    'captcha'               => 'Mã xác minh',
    'action'                => 'Hành động',
    'status'                => 'Trạng thái',
    'title'                 => 'Tiêu đề',
    'description'           => 'Mô tả',
    'back'                  => 'Trở về',
    'back_to_list'          => 'Danh sách trả lại',
    'submit'                => 'Submit',
    'menu'                  => 'Menu',
    'input'                 => 'Đầu vào',
    'succeeded'             => 'Thành công',
    'failed'                => 'Thất bại, đã có lỗi xảy ra',
    'delete_confirm'        => 'Bạn có chắc chắn muốn xóa?',
    'delete_succeeded'      => 'Đã xóa thành công !',
    'delete_failed'         => 'Xóa thất bại !',
    'update_succeeded'      => 'Cập nhật thành công !',
    'save_succeeded'        => 'Đã lưu thành công !',
    'refresh_succeeded'     => 'Làm mới thành công !',
    'login_successful'      => 'Đăng nhập thành công !',
    'choose'                => 'Chọn',
    'choose_file'           => 'Chọn tập tin',
    'choose_image'          => 'Chọn hình',
    'more'                  => 'Thêm',
    'deny'                  => 'Không có quyền truy cập',
    'administrator'         => 'Quản trị viên',
    'roles'                 => 'Vai trò',
    'image'                 => 'Hình ảnh',
    'permissions'           => 'Giấy phép',
    'slug'                  => 'slug',
    'update'                => 'Cập nhật',
    'created_at'            => 'Ngày tạo',
    'updated_at'            => 'Ngày cập nhật',
    'alert'                 => 'Chú ý',
    'parent_id'             => 'Menu cha',
    'sort'                  => 'Sắp xếp',
    'icon'                  => 'Biểu tượng',
    'url'                   => 'Đường dẫn',
    'operation_log'         => 'Nhật ký vận hành',
    'parent_select_error'   => 'Lỗi chọn phụ huynh',
    'pagination'            => [
        'range' => 'Từ :first đến :last ，Tổng cộng :total dòng',
    ],
    'role'                  => 'Vai trò',
    'permission'            => 'Giấy phép',
    'route'                 => 'Định tuyến',
    'confirm'               => 'Xác nhận',
    'cancel'                => 'Hủy bỏ',
    'http'                  => [
        'method' => 'HTTP方法',
        'path'   => 'HTTP路径',
    ],
    'all_methods_if_empty'  => 'Mặc định trống cho tất cả các phương thức',
    'all'                   => 'Tất cả',
    'current_page'          => 'Trang hiện tại',
    'selected_rows'         => 'Dòng được chọn',
    'upload'                => 'Tải lên',
    'new_folder'            => 'Thư mục mới',
    'time'                  => 'Thời gian',
    'size'                  => 'Kích thước',
    'listbox'               => [
        'text_total'         => 'Tổng cộng {0} Mục',
        'text_empty'         => 'Danh sách trống',
        'filtered'           => '{0} / {1}',
        'filter_clear'       => 'Hiển thị tất cả',
        'filter_placeholder' => 'Bộ lọc',
    ],
    'auth' => [

        'controller' => Encore\Admin\Controllers\AuthController::class,

        'guards' => [
            'admin' => [
                'driver' => 'session',
                'provider' => 'admin',
            ],
        ],

        'providers' => [
            'admin' => [
                'driver' => 'eloquent',
                'model' => Encore\Admin\Auth\Database\Administrator::class,
            ],
        ],
    ],
];

